fragment HomeParts on Home {
  __typename
  seo_title
  banner {
    __typename
    enabled
    heading
    text
    placeholder
    button
  }
  navbar {
    __typename
    logo
    cta_label
    cta_href
  }
  hero_background
  hero_heading
  hero_text
  hero_buttons {
    __typename
    label
    href
  }
  navbar_links {
    __typename
    label
    href
    dropdown
  }
  about {
    __typename
    tagline
    heading
    text
    image
    buttons {
      __typename
      label
      href
    }
  }
  menu {
    __typename
    tag
    heading
    text
    tabs {
      __typename
      id
      label
      tag
      heading
      text
      image
    }
  }
  testimonials {
    __typename
    heading
    text
    items {
      __typename
      quote
      stars
      avatar
      name
      role
    }
  }
  faq {
    __typename
    heading
    text
    items {
      __typename
      q
      a
    }
    still_heading
    still_text
    still_button
  }
  contact {
    __typename
    tagline
    heading
    text
    email
    phone
  }
}

fragment ConfigParts on Config {
  __typename
  seo {
    __typename
    title
    description
  }
  nav {
    __typename
    title
    link
  }
  footerNote
}
