name = "the-daily-grind"
account_id = "cbf48c78b17effd556df217fadc93cde"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[[kv_namespaces]]
binding = "hearth_otp"
id = "01efb54ec5c14675a154307580a35952"
preview_id = "3f4fa9476b4845e98f0b48abdb8c54cf"
